# Lexical Errors (LEX_xxx)
LEX_INVALID_CHAR = "LEX_001"
LEX_UNTERMINATED_STRING = "LEX_002"
LEX_UNTERMINATED_BLOCK = "LEX_003"
LEX_INVALID_NUMBER = "LEX_004"
LEX_INVALID_ESCAPE = "LEX_005"
LEX_UNTERMINATED_BEHAVIOR = "LEX_006"

# Syntax Errors (PAR_xxx)
PAR_EXPECTED_TOKEN = "PAR_001"
PAR_UNEXPECTED_TOKEN = "PAR_002"
PAR_INVALID_SYNTAX = "PAR_003"
PAR_UNEXPECTED_EOF = "PAR_004"
PAR_INDENTATION_ERROR = "PAR_005"
PAR_MULTIPLE_INTENTS = "PAR_006"

# Semantic Errors (SEM_xxx) - Future use
SEM_UNDEFINED_SYMBOL = "SEM_001"
SEM_REDEFINITION = "SEM_002"
SEM_TYPE_MISMATCH = "SEM_003"
