//! intrinsic 符号表——内置类型（全量 Rust 化·语义层：intrinsic 符号表）。
//!
//! 对应 Python 语义层的 intrinsic 符号表中的内置类型（CLASS 符号）。IBC 语言有固定
//! 的 42 个内置类型（int/float/str/bool/void/any/list/dict/tuple/... 等）。每个内置
//! 类型的 intrinsic 符号：uid = `intrinsic:<name>`，kind = CLASS，type_uid =
//! `type_root.<name>`，node_uid/owned_scope_uid = null，metadata = {}。
//!
//! 与 Python intrinsic 符号表逐条差分等价（34 语料）。内置函数/方法/模块归后续增量
//! （method = sym_anon_*，归类型解析后续）。

use std::collections::BTreeMap;

use serde_json::Value;

/// 42 个 IBC 内置类型（固定集，与 Python 语义层 intrinsic 符号表对齐）。
const BUILTIN_TYPES: &[&str] = &[
    "Enum",
    "Exception",
    "Intent",
    "LLMCallError",
    "LLMError",
    "LLMParseError",
    "LLMRetryExhaustedError",
    "None",
    "Optional",
    "ThreadCancelled",
    "ThreadError",
    "ThreadFailed",
    "any",
    "auto",
    "behavior",
    "bool",
    "bound_method",
    "chan",
    "dict",
    "environment",
    "float",
    "fn_callable",
    "generator",
    "int",
    "intent_context",
    "knowledge",
    "list",
    "llm_call_result",
    "llm_uncertain",
    "memory",
    "narrow_model",
    "quoted",
    "run_result",
    "slice",
    "slot",
    "str",
    "subscriber",
    "thread",
    "thread_result",
    "tuple",
    "vector",
    "void",
];

/// 19 个 IBC 内置函数（固定集，与 Python 语义层 intrinsic 符号表对齐）。
const BUILTIN_FUNCTIONS: &[&str] = &[
    "all",
    "callable",
    "copy",
    "deepcopy",
    "enumerate",
    "fn",
    "get_self_source",
    "len",
    "max",
    "min",
    "next",
    "print",
    "range",
    "reversed",
    "sorted",
    "sum",
    "tensor",
    "type",
    "vec",
    "zip",
];

/// 2 个 IBC 内置模块（固定集，与 Python 语义层 intrinsic 符号表对齐）。
const BUILTIN_MODULES: &[&str] = &["__string_exec__", "module"];

/// 构建单个 intrinsic 符号（uid = `intrinsic:<name>`，type_uid = `type_root.<name>`）。
pub fn class_parent(name: &str) -> Option<String> {
    CLASS_PARENTS.iter().find(|(n, _)| *n == name).map(|(_, p)| p.to_string())
}

const CLASS_PARENTS: &[(&str, &str)] = &[
    // 运行时错误类 → Exception（Python 契约：except Exception 捕获全部运行
    // 时错误——错误类继承链基类）
    ("InterpreterError", "Exception"),
    ("TypeError", "Exception"),
    ("ValueError", "Exception"),
    ("AttributeError", "Exception"),
    ("IndexError", "Exception"),
    ("KeyError", "Exception"),
    ("ZeroDivisionError", "Exception"),
    ("NameError", "Exception"),
    ("OverflowError", "Exception"),
    ("RecursionError", "Exception"),
    ("Enum", "Object"),
    ("Intent", "Object"),
    ("LLMCallError", "LLMError"),
    ("LLMError", "Exception"),
    ("LLMParseError", "LLMError"),
    ("LLMRetryExhaustedError", "LLMError"),
    ("ThreadCancelled", "ThreadError"),
    ("ThreadError", "Exception"),
    ("ThreadFailed", "ThreadError"),
    ("environment", "Object"),
    ("intent_context", "Object"),
    ("knowledge", "Object"),
    ("memory", "Object"),
    ("narrow_model", "Object"),
    ("quoted", "Object"),
    ("run_result", "Object"),
];

/// 函数类型静态签名表（name → ([参数类型名], 返回类型名)）——转录自 IBCI intrinsic
/// 函数声明（全语料实证稳定；含 bound_method 类型条目[固定 void 签名]）。
const FUNCTION_SIGS: &[(&str, &[&str], &str)] = &[
    ("all", &["any"], "bool"),
    ("bound_method", &[], "void"),
    ("callable", &[], "auto"),
    ("copy", &["any"], "any"),
    ("deepcopy", &["any"], "any"),
    ("enumerate", &["any"], "list"),
    ("eval", &["quoted"], "any"),
    ("fn", &[], "auto"),
    ("get_self_source", &[], "str"),
    ("len", &["any"], "int"),
    ("max", &["any"], "any"),
    ("min", &["any"], "any"),
    ("next", &["any"], "any"),
    ("print", &["any"], "void"),
    ("quote", &["str"], "quoted"),
    ("range", &["int"], "list"),
    ("reversed", &["any"], "list"),
    ("sorted", &["any"], "list"),
    ("sum", &["any"], "any"),
    ("type", &["any"], "str"),
    ("vec", &["list"], "vector"),
    ("tensor", &["list"], "any"),
    ("zip", &["any"], "list"),
];

/// 函数签名查表（name → ([参数类型名], 返回类型名)）——intrinsic 函数声明（from-
/// import 函数绑定的用户函数类型条目签名来源）。
pub fn function_sig(name: &str) -> Option<(Vec<String>, String)> {
    FUNCTION_SIGS
        .iter()
        .find(|(n, _, _)| *n == name)
        .map(|(_, p, r)| (p.iter().map(|s| s.to_string()).collect(), r.to_string()))
}

/// 方法声明签名查表（(base, method) → ([params], ret)）——公理层声明式方法表。
pub fn method_signature(base: &str, method: &str) -> Option<(Vec<String>, String)> {
    METHOD_SIGS
        .iter()
        .find(|(b, m, _, _)| *b == base && *m == method)
        .map(|(_, _, p, r)| (p.iter().map(|s| s.to_string()).collect(), r.to_string()))
}

/// 成员符号 canonical uid（与 Python FlatSerializer._collect_symbol 匿名符号内容哈希
/// 同构）：canonical JSON（**键字母序**——owned_scope_uid < owner_type_uid[d<r] +
/// compact 分隔）=
/// {"kind","metadata":{},"name","node_uid":null,"owned_scope_uid":null,
/// "owner_type_uid","type_uid":null} → sha256[:16] → sym_anon_<hash>。metadata = {}
/// （成员符号固定空 metadata，全语料实证）。
pub fn intrinsic_names() -> Vec<String> {
    let mut names = Vec::new();
    for n in BUILTIN_TYPES {
        names.push(n.to_string());
    }
    for n in BUILTIN_FUNCTIONS {
        names.push(n.to_string());
    }
    for n in BUILTIN_MODULES {
        names.push(n.to_string());
    }
    names
}


/// 类型成员静态表（35 类型 / 244 成员）——转录自 IBCI 公理层声明式成员表
/// （全语料实证跨语料稳定；泛型条目继承基类成员表[owner uid 区分]）。
/// (type name, [(member name, kind)])，类型名/成员名字母序（BTreeMap 同序）。
pub const METHOD_MEMBERS: &[(&str, &[(&str, &str)])] = &[
    ("Enum", &[("len", "method"), ("to_list", "method")]),
    ("Exception", &[("__to_prompt__", "method"), ("cast_to", "method"), ("message", "field")]),
    ("Intent", &[("get_content", "method"), ("get_mode", "method"), ("get_tag", "method")]),
    ("LLMCallError", &[("__to_prompt__", "method"), ("cast_to", "method"), ("message", "field"), ("provider_error", "field"), ("raw_response", "field")]),
    ("LLMError", &[("__to_prompt__", "method"), ("cast_to", "method"), ("message", "field"), ("raw_response", "field")]),
    ("LLMParseError", &[("__to_prompt__", "method"), ("cast_to", "method"), ("message", "field"), ("raw_response", "field"), ("type_name", "field")]),
    ("LLMRetryExhaustedError", &[("__to_prompt__", "method"), ("cast_to", "method"), ("max_retry", "field"), ("message", "field"), ("raw_response", "field")]),
    ("None", &[("cast_to", "method"), ("to_bool", "method")]),
    ("Optional", &[("__to_prompt__", "method"), ("cast_to", "method"), ("is_none", "method"), ("is_some", "method"), ("or_else", "method"), ("to_bool", "method"), ("unwrap", "method")]),
    ("ThreadCancelled", &[("__to_prompt__", "method"), ("cast_to", "method"), ("message", "field"), ("raw_response", "field")]),
    ("ThreadError", &[("__to_prompt__", "method"), ("cast_to", "method"), ("message", "field"), ("raw_response", "field")]),
    ("ThreadFailed", &[("__to_prompt__", "method"), ("cast_to", "method"), ("message", "field"), ("raw_response", "field")]),
    ("bool", &[("cast_to", "method"), ("to_bool", "method")]),
    ("chan", &[("close", "method"), ("recv", "method"), ("recv_nowait", "method"), ("send", "method"), ("send_nowait", "method"), ("subscribe", "method")]),
    ("dict", &[("__getitem__", "method"), ("__setitem__", "method"), ("cast_to", "method"), ("contains", "method"), ("get", "method"), ("items", "method"), ("keys", "method"), ("len", "method"), ("pop", "method"), ("remove", "method"), ("update", "method"), ("values", "method")]),
    ("environment", &[("clear", "method"), ("contains", "method"), ("fork", "method"), ("get", "method"), ("get_current", "method"), ("keys", "method"), ("len", "method"), ("pop", "method"), ("set", "method"), ("use", "method")]),
    ("float", &[("cast_to", "method"), ("to_bool", "method")]),
    ("generator", &[("generic_next", "method"), ("to_list", "method")]),
    ("int", &[("cast_to", "method"), ("to_bool", "method"), ("to_list", "method")]),
    ("intent_context", &[("__to_prompt__", "method"), ("clear", "method"), ("clear_inherited", "method"), ("combine", "method"), ("fork", "method"), ("get_current", "method"), ("merge", "method"), ("pop", "method"), ("push", "method"), ("resolve", "method"), ("use", "method")]),
    ("knowledge", &[("add_fact", "method"), ("all_in_world", "method"), ("amend", "method"), ("amend_fact", "method"), ("by_source", "method"), ("by_subject", "method"), ("cast_to", "method"), ("compare", "method"), ("contradicts", "method"), ("embed_search", "method"), ("embedding", "method"), ("embedding_dim", "method"), ("exists", "method"), ("expand", "method"), ("export", "method"), ("fact_len", "method"), ("facts", "method"), ("get", "method"), ("get_fact", "method"), ("has_embedding", "method"), ("history", "method"), ("history_fact", "method"), ("keys", "method"), ("len", "method"), ("lookup_pair", "method"), ("register_relation", "method"), ("register_word", "method"), ("register_world", "method"), ("relation", "method"), ("relations", "method"), ("retract", "method"), ("same_word", "method"), ("set_embedding", "method"), ("source", "method"), ("store", "method"), ("to_ibci", "method"), ("transitive", "method"), ("word", "method"), ("words", "method"), ("world", "method"), ("worlds", "method")]),
    ("list", &[("__getitem__", "method"), ("__setitem__", "method"), ("append", "method"), ("cast_to", "method"), ("clear", "method"), ("contains", "method"), ("count", "method"), ("index", "method"), ("insert", "method"), ("len", "method"), ("pop", "method"), ("remove", "method"), ("reverse", "method"), ("sort", "method")]),
    ("llm_uncertain", &[("__eq__", "method"), ("__ne__", "method"), ("__to_prompt__", "method"), ("cast_to", "method"), ("to_bool", "method")]),
    ("memory", &[("cast_to", "method"), ("consolidate", "method"), ("content_hash", "method"), ("corpus", "method"), ("demote", "method"), ("encode", "method"), ("export", "method"), ("keys", "method"), ("len", "method"), ("promote", "method"), ("prune", "method"), ("retrieve", "method"), ("search", "method"), ("set_capacity", "method"), ("snapshot", "method"), ("tier", "method"), ("tier_keys", "method"), ("tier_size", "method"), ("verify", "method")]),
    ("meta", &[("compile", "method"), ("eval", "method"), ("quote", "method")]),
    ("narrow_model", &[("__to_prompt__", "method"), ("architecture", "method"), ("cast_to", "method"), ("content_hash", "method"), ("dim", "method"), ("entities", "method"), ("name", "method"), ("relations", "method"), ("score", "method"), ("topk", "method")]),
    ("quoted", &[("__to_prompt__", "method"), ("cast_to", "method"), ("source", "field")]),
    ("run_result", &[("__to_prompt__", "method"), ("cast_to", "method"), ("exception", "field"), ("exit_status", "field"), ("stdout", "field")]),
    ("slot", &[("get", "method"), ("set", "method"), ("update", "method")]),
    ("str", &[("cast_to", "method"), ("contains", "method"), ("count", "method"), ("endswith", "method"), ("find", "method"), ("format", "method"), ("is_empty", "method"), ("join", "method"), ("len", "method"), ("lower", "method"), ("replace", "method"), ("rfind", "method"), ("split", "method"), ("startswith", "method"), ("strip", "method"), ("to_bool", "method"), ("upper", "method")]),
    ("subscriber", &[("close", "method"), ("recv", "method"), ("recv_nowait", "method")]),
    ("thread", &[("cancel", "method"), ("is_done", "method"), ("join", "method"), ("start", "method")]),
    ("thread_result", &[("error", "method"), ("expect", "method"), ("is_error", "method"), ("is_success", "method"), ("status", "method"), ("unwrap", "method"), ("unwrap_or", "method"), ("value", "method")]),
    ("tuple", &[("__getitem__", "method"), ("cast_to", "method"), ("len", "method")]),
    ("vector", &[("__getitem__", "method"), ("__to_prompt__", "method"), ("add", "method"), ("cast_to", "method"), ("cosine", "method"), ("dim", "method"), ("dot", "method"), ("dtype", "method"), ("ndim", "method"), ("norm", "method"), ("scale", "method"), ("shape", "method"), ("sub", "method"), ("to_list", "method")]),
];
/// 方法声明签名表（(base, method) → ([params], ret)）——转录自 IBCI 公理层
/// 声明式方法表（core/kernel/axioms/）；泛型特化另经 specialize_method_signature。
const METHOD_SIGS: &[(&str, &str, &[&str], &str)] = &[
    ("Enum", "len", &[], "int"),
    ("Enum", "to_list", &[], "list"),
    ("Exception", "__to_prompt__", &[], "str"),
    ("Exception", "cast_to", &["any"], "any"),
    ("Intent", "get_content", &[], "str"),
    ("Intent", "get_mode", &[], "str"),
    ("Intent", "get_tag", &[], "str"),
    ("LLMCallError", "__to_prompt__", &[], "str"),
    ("LLMCallError", "cast_to", &["any"], "any"),
    ("LLMError", "__to_prompt__", &[], "str"),
    ("LLMError", "cast_to", &["any"], "any"),
    ("LLMParseError", "__to_prompt__", &[], "str"),
    ("LLMParseError", "cast_to", &["any"], "any"),
    ("LLMRetryExhaustedError", "__to_prompt__", &[], "str"),
    ("LLMRetryExhaustedError", "cast_to", &["any"], "any"),
    ("None", "cast_to", &["any"], "any"),
    ("None", "to_bool", &[], "bool"),
    ("Optional", "__to_prompt__", &[], "str"),
    ("Optional", "cast_to", &["any"], "any"),
    ("Optional", "is_none", &[], "bool"),
    ("Optional", "is_some", &[], "bool"),
    ("Optional", "or_else", &["any"], "any"),
    ("Optional", "to_bool", &[], "bool"),
    ("Optional", "unwrap", &[], "any"),
    ("ThreadCancelled", "__to_prompt__", &[], "str"),
    ("ThreadCancelled", "cast_to", &["any"], "any"),
    ("ThreadError", "__to_prompt__", &[], "str"),
    ("ThreadError", "cast_to", &["any"], "any"),
    ("ThreadFailed", "__to_prompt__", &[], "str"),
    ("ThreadFailed", "cast_to", &["any"], "any"),
    ("bool", "cast_to", &["any"], "any"),
    ("bool", "to_bool", &[], "bool"),
    ("chan", "close", &[], "void"),
    ("chan", "recv", &[], "any"),
    ("chan", "recv_nowait", &[], "any"),
    ("chan", "send", &["any"], "void"),
    ("chan", "send_nowait", &["any"], "bool"),
    ("chan", "subscribe", &["int"], "subscriber"),
    ("dict", "__getitem__", &["any"], "any"),
    ("dict", "__setitem__", &["any", "any"], "void"),
    ("dict", "cast_to", &["any"], "any"),
    ("dict", "contains", &["any"], "bool"),
    ("dict", "get", &["any", "any"], "any"),
    ("dict", "items", &[], "list"),
    ("dict", "keys", &[], "list"),
    ("dict", "len", &[], "int"),
    ("dict", "pop", &["any"], "any"),
    ("dict", "remove", &["any"], "void"),
    ("dict", "update", &["any"], "void"),
    ("dict", "values", &[], "list"),
    ("environment", "clear", &[], "void"),
    ("environment", "contains", &["str"], "bool"),
    ("environment", "fork", &[], "environment"),
    ("environment", "get", &["str"], "any"),
    ("environment", "get_current", &[], "environment"),
    ("environment", "keys", &[], "list"),
    ("environment", "len", &[], "int"),
    ("environment", "pop", &["str"], "any"),
    ("environment", "set", &["str", "any"], "void"),
    ("environment", "use", &["environment"], "void"),
    ("file_handle", "cast_to", &["any"], "any"),
    ("file_handle", "close", &[], "void"),
    ("file_handle", "read", &[], "str"),
    ("file_handle", "read_bytes", &[], "any"),
    ("float", "cast_to", &["any"], "any"),
    ("float", "to_bool", &[], "bool"),
    ("generator", "generic_next", &[], "any"),
    ("generator", "to_list", &[], "list"),
    ("int", "cast_to", &["any"], "any"),
    ("int", "to_bool", &[], "bool"),
    ("int", "to_list", &[], "list"),
    ("intent_context", "__to_prompt__", &[], "str"),
    ("intent_context", "clear", &[], "void"),
    ("intent_context", "clear_inherited", &[], "void"),
    ("intent_context", "combine", &["intent_context"], "void"),
    ("intent_context", "fork", &[], "intent_context"),
    ("intent_context", "get_current", &[], "intent_context"),
    ("intent_context", "merge", &["intent_context"], "void"),
    ("intent_context", "pop", &[], "any"),
    ("intent_context", "push", &["any"], "void"),
    ("intent_context", "resolve", &[], "any"),
    ("intent_context", "use", &["intent_context"], "void"),
    ("knowledge", "add_fact", &["str", "str", "str", "str", "str", "str"], "str"),
    ("knowledge", "all_in_world", &["str"], "list"),
    ("knowledge", "amend", &["str", "any", "str"], "void"),
    ("knowledge", "amend_fact", &["str", "str", "str"], "void"),
    ("knowledge", "by_source", &["str"], "list"),
    ("knowledge", "by_subject", &["str"], "list"),
    ("knowledge", "cast_to", &["any"], "any"),
    ("knowledge", "compare", &["str", "str"], "dict"),
    ("knowledge", "contradicts", &["str", "str", "str"], "bool"),
    ("knowledge", "embed_search", &["vector", "int"], "list"),
    ("knowledge", "embedding", &["str"], "vector"),
    ("knowledge", "embedding_dim", &[], "int"),
    ("knowledge", "exists", &["str", "str", "str", "str"], "bool"),
    ("knowledge", "expand", &["str"], "dict"),
    ("knowledge", "export", &[], "dict"),
    ("knowledge", "fact_len", &[], "int"),
    ("knowledge", "facts", &[], "list"),
    ("knowledge", "get", &["str"], "any"),
    ("knowledge", "get_fact", &["str"], "any"),
    ("knowledge", "has_embedding", &["str"], "bool"),
    ("knowledge", "history", &["str", "str"], "list"),
    ("knowledge", "history_fact", &["str"], "list"),
    ("knowledge", "keys", &[], "list"),
    ("knowledge", "len", &[], "int"),
    ("knowledge", "lookup_pair", &["str", "str"], "list"),
    ("knowledge", "register_relation", &["str", "str", "bool", "bool"], "void"),
    ("knowledge", "register_word", &["str", "str", "bool", "list", "dict"], "void"),
    ("knowledge", "register_world", &["str", "str", "int"], "void"),
    ("knowledge", "relation", &["str"], "any"),
    ("knowledge", "relations", &[], "list"),
    ("knowledge", "retract", &["str", "str"], "void"),
    ("knowledge", "same_word", &["str", "str"], "bool"),
    ("knowledge", "set_embedding", &["str", "vector"], "void"),
    ("knowledge", "source", &["str"], "str"),
    ("knowledge", "store", &["str", "any", "any", "str"], "void"),
    ("knowledge", "to_ibci", &[], "str"),
    ("knowledge", "transitive", &["str", "str"], "list"),
    ("knowledge", "word", &["str"], "any"),
    ("knowledge", "words", &[], "list"),
    ("knowledge", "world", &["str"], "any"),
    ("knowledge", "worlds", &[], "list"),
    ("list", "__getitem__", &["int"], "any"),
    ("list", "__setitem__", &["int", "any"], "void"),
    ("list", "append", &["any"], "void"),
    ("list", "cast_to", &["any"], "any"),
    ("list", "clear", &[], "void"),
    ("list", "contains", &["any"], "bool"),
    ("list", "count", &["any"], "int"),
    ("list", "index", &["any"], "int"),
    ("list", "insert", &["int", "any"], "void"),
    ("list", "len", &[], "int"),
    ("list", "pop", &[], "any"),
    ("list", "remove", &["any"], "void"),
    ("list", "reverse", &[], "void"),
    ("list", "sort", &[], "void"),
    ("llm_uncertain", "__eq__", &["any"], "bool"),
    ("llm_uncertain", "__ne__", &["any"], "bool"),
    ("llm_uncertain", "__to_prompt__", &[], "str"),
    ("llm_uncertain", "cast_to", &["any"], "any"),
    ("llm_uncertain", "to_bool", &[], "bool"),
    ("memory", "cast_to", &["any"], "any"),
    ("memory", "consolidate", &["dict"], "int"),
    ("memory", "content_hash", &["str"], "str"),
    ("memory", "corpus", &["str"], "list"),
    ("memory", "demote", &["str", "str"], "void"),
    ("memory", "encode", &["str", "any", "str", "str"], "void"),
    ("memory", "export", &[], "dict"),
    ("memory", "keys", &[], "list"),
    ("memory", "len", &[], "int"),
    ("memory", "promote", &["str", "str"], "void"),
    ("memory", "prune", &["dict"], "int"),
    ("memory", "retrieve", &["str"], "any"),
    ("memory", "search", &["str", "str", "int"], "list"),
    ("memory", "set_capacity", &["str", "any"], "void"),
    ("memory", "snapshot", &[], "dict"),
    ("memory", "tier", &["str"], "str"),
    ("memory", "tier_keys", &["str"], "list"),
    ("memory", "tier_size", &["str"], "int"),
    ("memory", "verify", &["str"], "bool"),
    ("narrow_model", "__to_prompt__", &[], "str"),
    ("narrow_model", "architecture", &[], "str"),
    ("narrow_model", "cast_to", &["any"], "any"),
    ("narrow_model", "content_hash", &[], "str"),
    ("narrow_model", "dim", &[], "int"),
    ("narrow_model", "entities", &[], "list"),
    ("narrow_model", "name", &[], "str"),
    ("narrow_model", "relations", &[], "list"),
    ("narrow_model", "score", &["str", "str", "str"], "float"),
    ("narrow_model", "topk", &["str", "str", "int"], "list"),
    ("quoted", "__to_prompt__", &[], "str"),
    ("quoted", "cast_to", &["any"], "any"),
    ("run_result", "__to_prompt__", &[], "str"),
    ("run_result", "cast_to", &["any"], "any"),
    ("slot", "get", &[], "any"),
    ("slot", "set", &["any"], "void"),
    ("slot", "update", &["any"], "void"),
    ("str", "cast_to", &["any"], "any"),
    ("str", "contains", &["str"], "bool"),
    ("str", "count", &["str", "int"], "int"),
    ("str", "endswith", &["str"], "bool"),
    ("str", "find", &["str", "int"], "int"),
    ("str", "format", &["any"], "str"),
    ("str", "is_empty", &[], "bool"),
    ("str", "join", &["list"], "str"),
    ("str", "len", &[], "int"),
    ("str", "lower", &[], "str"),
    ("str", "replace", &["str", "str"], "str"),
    ("str", "rfind", &["str", "int"], "int"),
    ("str", "split", &["str"], "list"),
    ("str", "startswith", &["str"], "bool"),
    ("str", "strip", &[], "str"),
    ("str", "to_bool", &[], "bool"),
    ("str", "upper", &[], "str"),
    ("subscriber", "close", &[], "void"),
    ("subscriber", "recv", &[], "any"),
    ("subscriber", "recv_nowait", &[], "any"),
    ("thread", "cancel", &[], "any"),
    ("thread", "is_done", &[], "bool"),
    ("thread", "join", &[], "any"),
    ("thread", "start", &[], "thread"),
    ("thread_result", "error", &[], "any"),
    ("thread_result", "expect", &[], "any"),
    ("thread_result", "is_error", &[], "bool"),
    ("thread_result", "is_success", &[], "bool"),
    ("thread_result", "status", &[], "str"),
    ("thread_result", "unwrap", &[], "any"),
    ("thread_result", "unwrap_or", &["any"], "any"),
    ("thread_result", "value", &[], "any"),
    ("tuple", "__getitem__", &["int"], "any"),
    ("tuple", "cast_to", &["any"], "any"),
    ("tuple", "len", &[], "int"),
    ("vector", "__getitem__", &["int"], "float"),
    ("vector", "__to_prompt__", &[], "str"),
    ("vector", "add", &["vector"], "vector"),
    ("vector", "cast_to", &["any"], "any"),
    ("vector", "cosine", &["vector"], "float"),
    ("vector", "dim", &[], "int"),
    ("vector", "dtype", &[], "str"),
    ("vector", "ndim", &[], "int"),
    ("vector", "shape", &[], "list"),
    ("vector", "to_list", &[], "list"),
    ("vector", "dot", &["vector"], "float"),
    ("vector", "norm", &[], "float"),
    ("vector", "scale", &["float"], "vector"),
    ("vector", "sub", &["vector"], "vector"),
];
