from typing import Any, Protocol, List, Dict, Callable, Optional, Type, Union, runtime_checkable, Mapping
from core.domain import ast as ast
from core.foundation.interfaces import (
    IssueTracker, IStackInspector, ISourceProvider, ICompilerService
)

@runtime_checkable
class Registry(Protocol):
    """类与实例注册表接口"""
    def get_class(self, name: str) -> Any: ...
    def box(self, value: Any, memo: Optional[Dict[int, Any]] = None) -> Any: ...

# --- Runtime Value Symbols ---

class RuntimeSymbol(Protocol):
    """运行时符号，包含值和类型信息"""
    name: str
    value: Any
    declared_type: Any  # IBC-Inter 类型 (int, float, str, list, dict, var, etc.)
    current_type: Any   # 运行时实际类型
    is_const: bool      # 是否为常量（内置函数等）

class SymbolView(Protocol):
    """只读符号视图接口"""
    def get(self, name: str) -> Any: ...
    def get_symbol(self, name: str) -> Optional[RuntimeSymbol]: ...
    def has(self, name: str) -> bool: ...

# --- Scope & Context ---

class Scope(Protocol):
    """运行时作用域接口"""
    def define(self, name: str, value: Any, declared_type: Any = None, is_const: bool = False, uid: Optional[str] = None, force: bool = False) -> None: ...
    def assign(self, name: str, value: Any) -> bool: ...
    def get(self, name: str) -> Any: ...
    def get_symbol(self, name: str) -> Optional[RuntimeSymbol]: ...
    def get_all_symbols(self) -> Dict[str, RuntimeSymbol]: ...
    @property
    def parent(self) -> Optional['Scope']: ...

class RuntimeContext(Protocol):
    """解释器运行时上下文，管理作用域和意图栈"""
    def enter_scope(self) -> None: ...
    def exit_scope(self) -> None: ...
    def define_variable(self, name: str, value: Any, declared_type: Any = None, is_const: bool = False, uid: Optional[str] = None, force: bool = False) -> None: ...
    def set_variable(self, name: str, value: Any) -> None: ...
    def get_variable(self, name: str) -> Any: ...
    def get_symbol(self, name: str) -> Optional[RuntimeSymbol]: ...
    def get_vars(self) -> Dict[str, Any]: ...
    
    # 意图管理 (三层架构: Global, Block, Call)
    def set_global_intent(self, intent: 'IbIntent') -> None: ...
    def clear_global_intents(self) -> None: ...
    def remove_global_intent(self, intent: Union[str, 'IbIntent']) -> None: ...
    def get_global_intents(self) -> List['IbIntent']: ...
    
    # 意图屏蔽控制 (Block 级别)
    def enter_intent_exclusive_scope(self) -> None: ...
    def exit_intent_exclusive_scope(self) -> None: ...
    def is_intent_exclusive(self) -> bool: ...
    
    def push_intent(self, intent: Union[str, 'IbIntent'], mode: str = "+", tag: Optional[str] = None) -> None: ...
    def pop_intent(self) -> Optional['IbIntent']: ...
    def get_active_intents(self) -> List['IbIntent']: ...
    def get_resolved_prompt_intents(self, execution_context: 'IExecutionContext', call_intent: Optional['IbIntent'] = None) -> List[str]: ...
    
    @property
    def intent_stack(self) -> List['ast.IbIntentInfo']: ...
    
    # 循环上下文注入
    def push_loop_context(self, index: int, total: int) -> None: ...
    def pop_loop_context(self) -> None: ...
    def get_loop_context(self) -> Optional[Dict[str, int]]: ...
    
    @property
    def current_scope(self) -> Scope: ...
    @property
    def global_scope(self) -> Scope: ...

    @property
    def registry(self) -> Any: ...

    def get_symbol_view(self) -> SymbolView: ...

# --- Components ---

class LLMExecutor(Protocol):
    """LLM 执行组件，负责构建 Prompt 并调用 LLM"""
    def execute_llm_function(self, node_uid: str, execution_context: 'IExecutionContext') -> Any: ...
    def execute_behavior_expression(self, node_uid: str, execution_context: 'IExecutionContext', captured_intents: Optional[List[str]] = None) -> Any: ...
    def get_last_call_info(self) -> Mapping[str, Any]: ...

class InterOp(Protocol):
    """Python 互操作组件，负责 Python 函数/类的映射和命名空间隔离"""
    def register_package(self, name: str, obj: Any) -> None: ...
    def get_package(self, name: str) -> Optional[Any]: ...
    def wrap_python_function(self, func: Callable) -> Callable: ...

class ModuleManager(Protocol):
    """模块管理组件，负责 import 逻辑"""
    def import_module(self, module_name: str, execution_context: 'IExecutionContext') -> Any: ...
    def import_from(self, module_name: str, names: List[tuple], execution_context: 'IExecutionContext') -> None: ...

class ModuleInstance(Protocol):
    """IBC-Inter 模块实例，表示一个已执行模块的运行时状态"""
    name: str
    scope: Scope
    def get_variable(self, name: str) -> Any: ...

class PermissionManager(Protocol):
    """权限管理组件，负责沙箱路径校验"""
    def validate_path(self, path: str, operation: str = "access") -> None: ...
    def enable_external_access(self) -> None: ...
    def is_external_access_enabled(self) -> bool: ...

class IHostService(Protocol):
    """内核级宿主服务子系统接口"""
    def sync(self) -> None: ...
    def save_state(self, path: str) -> None: ...
    def load_state(self, path: str) -> None: ...
    def run_isolated(self, path: str, policy: Dict[str, Any]) -> bool: ...
    def get_source(self) -> str: ...

class IInterpreterFactory(Protocol):
    """
    解释器实例工厂接口。
    用于解决 HostService 与 Interpreter 之间的物理循环依赖。
    """
    def spawn_interpreter(self, 
                          artifact: Any, 
                          registry: Any, 
                          host_interface: Any,
                          root_dir: str,
                          parent_context: 'RuntimeContext') -> 'Interpreter': ...

@runtime_checkable
class IIbObject(Protocol):
    """IBC-Inter 对象基础协议 (Everything is an Object)"""
    @property
    def ib_class(self) -> 'IIbClass': ...
    @property
    def fields(self) -> Mapping[str, Any]: ...
    @property
    def descriptor(self) -> Any: ... # TypeDescriptor
    def receive(self, message: str, args: List['IIbObject']) -> 'IIbObject': ...
    def to_native(self, memo: Optional[Dict[int, Any]] = None) -> Any: ...
    def __to_prompt__(self) -> str: ...

@runtime_checkable
class IIbClass(IIbObject, Protocol):
    """IBC-Inter 类/元对象协议"""
    name: str
    parent: Optional['IIbClass']
    registry: Any # Registry
    def lookup_method(self, name: str) -> Optional['IIbFunction']: ...
    def register_method(self, name: str, method: 'IIbFunction') -> None: ...
    def instantiate(self, args: List['IIbObject'], context: Optional['IExecutionContext'] = None) -> 'IIbObject': ...

@runtime_checkable
class IIbFunction(IIbObject, Protocol):
    """IBC-Inter 可调用对象协议"""
    def call(self, receiver: 'IIbObject', args: List['IIbObject']) -> 'IIbObject': ...

@runtime_checkable
class IIbList(IIbObject, Protocol):
    """IBC-Inter 列表对象协议"""
    elements: List['IIbObject']
    def append(self, item: 'IIbObject') -> 'IIbObject': ...
    def pop(self) -> 'IIbObject': ...
    def len(self) -> 'IIbObject': ...

@runtime_checkable
class IIbIntent(IIbObject, Protocol):
    """IBC-Inter 意图对象协议"""
    content: str
    mode: Any # IntentMode
    tag: Optional[str]
    role: Any # IntentRole
    def resolve_content(self, context: 'RuntimeContext', execution_context: 'IExecutionContext') -> str: ...

@runtime_checkable
class IIbModule(IIbObject, Protocol):
    """IBC-Inter 模块对象协议"""
    name: str
    scope: 'Scope'

class IObjectFactory(Protocol):
    """
    运行时对象工厂接口。
    用于解耦 Service（如 ModuleManager）与具体运行时对象（如 IbModule）的构造。
    """
    def create_module(self, name: str, scope: 'Scope') -> 'IIbModule': ...
    def create_scope(self, parent: Optional['Scope'] = None) -> 'Scope': ...
    def create_native_object(self, py_obj: Any, ib_class: 'IIbClass', vtable: Optional[Dict[str, Any]] = None) -> 'IIbObject': ...
    def create_behavior(self, node_uid: str, captured_intents: List[Any], expected_type: Optional[str] = None) -> Any: ...
    def create_list(self, elements: List['IIbObject']) -> 'IIbList': ...
    def create_intent(self, content: str = "", mode: Any = None, tag: Optional[str] = None, role: Any = None) -> 'IIbIntent': ...
    def create_intent_from_node(self, node_uid: str, node_data: Mapping[str, Any], role: Any = None) -> 'IIbIntent': ...

# --- Service Context ---

@runtime_checkable
class ServiceContext(Protocol):
    """注入容器，聚合所有运行时服务"""
    @property
    def registry(self) -> Any: ...
    @property
    def issue_tracker(self) -> IssueTracker: ...
    @property
    def llm_executor(self) -> LLMExecutor: ...
    @property
    def module_manager(self) -> ModuleManager: ...
    @property
    def object_factory(self) -> IObjectFactory: ...
    @property
    def interop(self) -> InterOp: ...
    @property
    def permission_manager(self) -> PermissionManager: ...
    @property
    def host_service(self) -> Optional[IHostService]: ...
    @property
    def source_provider(self) -> Optional[ISourceProvider]: ...
    @property
    def compiler(self) -> Optional[ICompilerService]: ...
    @property
    def debugger(self) -> Any: ...

@runtime_checkable
class IModuleLoader(Protocol):
    """模块加载器接口 (ModuleLoader)"""
    def load_and_register_all(self, context: ServiceContext, execution_context: 'IExecutionContext') -> None: ...

# --- Main Interpreter ---

class Interpreter(Protocol):
    """IBC-Inter 解释器协议"""
    @property
    def runtime_context(self) -> RuntimeContext: ...
    @property
    def registry(self) -> Any: ...
    @property
    def symbol_view(self) -> SymbolView: ...
    def visit(self, node_uid: str) -> Any: ...
    def get_node_data(self, node_uid: str) -> Mapping[str, Any]: ...
    def get_side_table(self, table_name: str, key: str) -> Any: ...
    def execute_module(self, root_node_uid: str, module_name: str, scope: Any): ...
