from typing import Any, Protocol, List, Dict, Callable, Optional, Type, Union, runtime_checkable, Mapping, TYPE_CHECKING, Tuple
from dataclasses import dataclass, field

if TYPE_CHECKING:
    from core.kernel import ast as ast

from core.base.interfaces import (
    IssueTracker, ISourceProvider, ICompilerService
)

from core.kernel.interfaces import IExecutionContext

@runtime_checkable
class IStackInspector(Protocol):
    """提供对调用栈和意图栈的内省能力"""
    def get_call_stack_depth(self) -> int: ...
    def get_active_intents(self) -> List[str]: ...
    def get_instruction_count(self) -> int: ...
    def get_captured_intents(self, obj: Any) -> List[str]: ...
    def get_current_script_path(self) -> Optional[str]: ...
    def get_current_script_dir(self) -> Optional[str]: ...

@runtime_checkable
class Registry(Protocol):
    """类与实例注册表接口"""
    def get_class(self, name: str) -> Any: ...
    def box(self, value: Any, memo: Optional[Dict[int, Any]] = None) -> Any: ...

class RuntimeSymbol(Protocol):
    """运行时符号，包含值和类型信息"""
    name: str
    value: Any
    declared_type: Any
    current_type: Any
    is_const: bool
    is_builtin: bool  # L2：内置函数（intrinsic）符号标志，由 IntrinsicManager 注入

class SymbolView(Protocol):
    """只读符号视图接口"""
    def get(self, name: str) -> Any: ...
    def get_symbol(self, name: str) -> Optional[RuntimeSymbol]: ...
    def has(self, name: str) -> bool: ...

class Scope(Protocol):
    """运行时作用域接口"""
    def define(self, name: str, value: Any, declared_type: Any = None, is_const: bool = False, uid: Optional[str] = None, force: bool = False, is_builtin: bool = False) -> None: ...
    def assign(self, name: str, value: Any) -> bool: ...
    def get(self, name: str) -> Any: ...
    def get_symbol(self, name: str) -> Optional[RuntimeSymbol]: ...
    def get_all_symbols(self) -> Dict[str, RuntimeSymbol]: ...
    @property
    def parent(self) -> Optional['Scope']: ...
    def iter_cells(self) -> Any:
        """
        枚举本作用域（不递归父）已提升为 IbCell 的变量条目（公理 GC-2 根集合扫描入口）。
        默认实现返回空迭代器；具体作用域类型若支持 Cell 提升应覆写此方法。
        """
        return iter(())
    def is_cell_promoted(self, sym_uid: str) -> bool:
        """判断 sym_uid 是否已提升为 Cell 变量（C12 封装替代私有 _cell_map 探测）。

        默认返回 False；支持 Cell 提升的 ScopeImpl 应覆写此方法。
        """
        return False
    def define_raw(self, name: Optional[str], value: Any, uid: Optional[str] = None, declared_type: Any = None) -> Any:
        """低级符号写入，绕过类型检查（VM 特殊路径专用，C12）。

        默认实现委托到 define()；支持 LLMFuture 占位符写入的 ScopeImpl 应覆写此方法。
        """
        self.define(name or "", value, uid=uid)
        return None

class RuntimeContext(Protocol):
    """解释器运行时上下文，管理作用域和意图栈"""
    def enter_scope(self) -> None: ...
    def exit_scope(self) -> None: ...
    def define_variable(self, name: str, value: Any, declared_type: Any = None, is_const: bool = False, uid: Optional[str] = None, force: bool = False, is_builtin: bool = False) -> None: ...
    def set_variable(self, name: str, value: Any) -> None: ...
    def get_variable(self, name: str) -> Any: ...
    def get_symbol(self, name: str) -> Optional[RuntimeSymbol]: ...
    def get_vars(self) -> Dict[str, Any]: ...

    def set_global_intent(self, intent: 'IbIntent') -> None: ...
    def clear_global_intents(self) -> None: ...
    def remove_global_intent(self, intent: Union[str, 'IbIntent']) -> None: ...
    def get_global_intents(self) -> List['IbIntent']: ...

    def enter_intent_exclusive_scope(self) -> None: ...
    def exit_intent_exclusive_scope(self) -> None: ...
    def is_intent_exclusive(self) -> bool: ...

    def push_intent(self, intent: Union[str, 'IbIntent'], mode: str = "+", tag: Optional[str] = None) -> None: ...
    def pop_intent(self) -> Optional['IbIntent']: ...
    def get_active_intents(self) -> List['IbIntent']: ...
    def add_smear_intent(self, intent: 'IbIntent') -> None: ...
    def get_resolved_prompt_intents(self, execution_context: IExecutionContext, call_intent: Optional['IbIntent'] = None) -> List[str]: ...

    @property
    def intent_stack(self) -> List['ast.IbIntentInfo']: ...

    def push_loop_context(self, index: int, total: int) -> None: ...
    def pop_loop_context(self) -> None: ...
    def get_loop_context(self) -> Optional[Dict[str, int]]: ...

    @property
    def current_scope(self) -> Scope: ...
    @property
    def global_scope(self) -> Scope: ...

    @property
    def retry_hint(self) -> Optional[str]: ...
    @retry_hint.setter
    def retry_hint(self, value: Optional[str]) -> None: ...

    @property
    def registry(self) -> Any: ...

    def get_symbol_view(self) -> SymbolView: ...

class LLMExecutor(Protocol):
    """LLM 执行组件，负责构建 Prompt 并调用 LLM"""
    def execute_llm_function(self, node_uid: str, execution_context: IExecutionContext) -> Any: ...
    def execute_behavior_expression(self, node_uid: str, execution_context: IExecutionContext, captured_intents: Optional[List[str]] = None) -> Any: ...
    def get_last_call_info(self) -> Mapping[str, Any]: ...

class InterOp(Protocol):
    """Python 互操作组件，负责 Python 函数/类的映射和命名空间隔离"""
    @property
    def metadata(self) -> Any: ... # Returns MetadataRegistry

    def register_package(self, name: str, obj: Any, metadata: Optional[Any] = None, discovery_name: Optional[str] = None) -> None: ...
    def get_package(self, name: str) -> Optional[Any]: ...
    def get_discovery_name(self, module_name: str) -> Optional[str]: ...
    def get_module_name_by_discovery(self, discovery_name: str) -> Optional[str]: ...
    def get_all_package_names(self) -> List[str]: ...
    def wrap_python_function(self, func: Callable) -> Callable: ...

class ModuleManager(Protocol):
    """模块管理组件，负责 import 逻辑"""
    def import_module(self, module_name: str, execution_context: IExecutionContext) -> Any: ...
    def import_from(self, module_name: str, names: List[tuple], execution_context: IExecutionContext) -> None: ...

class ModuleInstance(Protocol):
    """IBC-Inter 模块实例，表示一个已执行模块的运行时状态"""
    name: str
    scope: Scope
    def get_variable(self, name: str) -> Any: ...

class PermissionManager(Protocol):
    """权限管理组件，负责沙箱路径校验"""
    @property
    def root_dir(self) -> str: ...
    def validate_path(self, path: str, operation: str = "access") -> None: ...
    def enable_external_access(self) -> None: ...
    def is_external_access_enabled(self) -> bool: ...

class IHostService(Protocol):
    """内核级宿主服务子系统接口"""
    def sync(self) -> None: ...
    def save_state(self, path: str) -> None: ...
    def load_state(self, path: str) -> None: ...
    def run_isolated(self, path: str, policy: Dict[str, Any]) -> bool: ...
    def spawn_isolated(self, path: str, policy: Dict[str, Any]) -> str: ...
    def collect(self, handle: str) -> Dict[str, Any]: ...
    def get_source(self) -> str: ...

class IKernelOrchestrator(Protocol):
    """
     内核协调器协议。
    定义了运行时环境向引擎层（Host/Engine）发起的最高特权系统调用。
    用于解决架构穿透问题，使运行时无需感知 Compiler 等底层构建组件。
    """
    def request_isolated_run(self, entry_path: str, policy: Dict[str, Any], initial_vars: Optional[Dict[str, Any]] = None) -> bool: ...
    def request_spawn_isolated(self, entry_path: str, policy: Dict[str, Any], initial_vars: Optional[Dict[str, Any]] = None) -> str: ...
    def request_collect(self, handle: str) -> Dict[str, Any]: ...

class IInterpreterFactory(Protocol):
    """
    解释器实例工厂接口。
    用于解决 HostService 与 Interpreter 之间的物理循环依赖。
    """
    def spawn_interpreter(self,
                          artifact: Any,
                          registry: Any,
                          host_interface: Any,
                          root_dir: str,
                          parent_context: RuntimeContext,
                          isolated: bool = False) -> 'Interpreter': ...

    def create_compiler(self, root_dir: str, host_interface: Any, registry: Any) -> ICompilerService: ...

@runtime_checkable
class IIbObject(Protocol):
    """IBC-Inter 对象基础协议 (Everything is an Object)"""
    @property
    def ib_class(self) -> 'IIbClass': ...
    @property
    def fields(self) -> Mapping[str, Any]: ...
    def receive(self, message: str, args: List['IIbObject']) -> 'IIbObject': ...
    def to_native(self, memo: Optional[Dict[int, Any]] = None) -> Any: ...
    def __to_prompt__(self) -> str: ...
    def __from_prompt__(self, raw_response: str) -> Tuple[bool, Any]:
        """
        从 LLM 返回的原始文本中解析值。

        Returns:
            (True, parsed_value) - 解析成功
            (False, retry_hint)  - 解析失败，retry_hint 用于提示重试方向
        """
        ...
    def __outputhint_prompt__(self) -> str:
        """
        返回期望的 LLM 输出格式描述。
        用于提示词注入，告诉 LLM 应该输出什么格式。
        """
        ...

@runtime_checkable
class IIbClass(IIbObject, Protocol):
    """IBC-Inter 类/元对象协议"""
    name: str
    parent: Optional['IIbClass']
    registry: Any
    def lookup_method(self, name: str) -> Optional['IIbFunction']: ...
    def register_method(self, name: str, method: 'IIbFunction') -> None: ...
    def instantiate(self, args: List['IIbObject'], context: Optional[IExecutionContext] = None) -> 'IIbObject': ...

@runtime_checkable
class IIbFunction(IIbObject, Protocol):
    """IBC-Inter 可调用对象协议"""
    def call(self, receiver: 'IIbObject', args: List['IIbObject']) -> 'IIbObject': ...

@runtime_checkable
class IIbList(IIbObject, Protocol):
    """IBC-Inter 列表对象协议"""
    elements: List['IIbObject']
    def append(self, item: 'IIbObject') -> 'IIbObject': ...
    def pop(self) -> 'IIbObject': ...
    def len(self) -> 'IIbObject': ...

@runtime_checkable
class IIbIntent(IIbObject, Protocol):
    """IBC-Inter 意图对象协议"""
    content: str
    mode: Any
    tag: Optional[str]
    role: Any
    def resolve_content(self, context: RuntimeContext, execution_context: IExecutionContext) -> str: ...

@runtime_checkable
class IIbBehavior(IIbObject, Protocol):
    """延迟执行的行为对象协议 (~...~)

    ``captured_intents``:
      - ``None``：lambda 模式（调用时使用当前上下文意图栈）
      - ``IbIntentContext`` 实例：snapshot 模式 / dispatch_eager（已 fork 的值快照）

    历史的 IntentNode 链表 / 已展平 list 路径自 Step 6c/6d 起已废弃。
    """
    node: str
    captured_intents: Optional[Any]  # Optional[IbIntentContext]; Any 避免循环导入
    expected_type: Optional[str]

@runtime_checkable
class IIbModule(IIbObject, Protocol):
    """IBC-Inter 模块对象协议"""
    name: str
    scope: 'Scope'

class IObjectFactory(Protocol):
    """
    运行时对象工厂接口。
    用于解耦 Service（如 ModuleManager）与具体运行时对象（如 IbModule）的构造。
    """
    def create_module(self, name: str, scope: 'Scope') -> 'IIbModule': ...
    def create_scope(self, parent: Optional['Scope'] = None) -> 'Scope': ...
    def create_native_object(self, py_obj: Any, ib_class: 'IIbClass', vtable: Optional[Dict[str, Any]] = None) -> 'IIbObject': ...
    def create_behavior(self, node_uid: str, captured_intents: List[Any], expected_type: Optional[str] = None, call_intent: Optional[Any] = None, deferred_mode: Optional[str] = None, execution_context: Optional[Any] = None, params_uids: Optional[List[str]] = None, closure: Optional[Dict[str, Any]] = None) -> Any: ...
    def create_deferred(self, node_uid: str, deferred_mode: str = "lambda", execution_context: Optional[Any] = None, params_uids: Optional[List[str]] = None, body_uid: Optional[str] = None, closure: Optional[Dict[str, Any]] = None) -> Any: ...
    def create_list(self, elements: List['IIbObject']) -> 'IIbList': ...
    def create_intent(self, content: str = "", mode: Any = None, tag: Optional[str] = None, role: Any = None) -> 'IIbIntent': ...
    def create_intent_from_node(self, node_uid: str, node_data: Mapping[str, Any], role: Any = None) -> 'IIbIntent': ...
    def create_context(self, initial_scope: Optional['Scope'] = None) -> 'RuntimeContext': ...
    def create_runtime_symbol(self, name: str, value: Any, declared_type: Any = None, is_const: bool = False) -> 'RuntimeSymbol': ...

    def register_handler_factory(self, factory: Callable) -> None: ...
    def register_llm_executor_factory(self, factory: Callable) -> None: ...
    def create_handlers(self, service_context: 'ServiceContext', execution_context: IExecutionContext) -> List[Any]: ...
    def create_llm_executor(self, service_context: 'ServiceContext', execution_context: IExecutionContext) -> 'LLMExecutor': ...

@runtime_checkable
class IStateProvider(Protocol):
    """提供运行时状态的只读镜像，用于解耦序列化逻辑"""
    def get_current_scope(self) -> Scope: ...
    def get_global_intents(self) -> List[Any]: ...
    def get_active_intents(self) -> List[Any]: ...
    @property
    def intent_exclusive_depth(self) -> int: ...

class IsolationLevel:
    """隔离级别定义"""
    NONE = "none"           # 无隔离，共享所有状态
    SCOPE = "scope"         # 仅隔离局部作用域，共享全局作用域和 Registry
    REGISTRY = "registry"   # 隔离 Registry，共享内核公理
    PROCESS = "process"     # 完全隔离 (未来扩展)

@dataclass
class ExecutionSignal:
    """执行信号，用于跨实例/宏观调度"""
    type: str               # "return", "break", "continue", "retry", "exit"
    value: Any = None       # 携带的值
    node_uid: Optional[str] = None # 信号触发位置

@dataclass
class ExecutionRequest:
    """执行请求，由解释器向调度器发起"""
    node_uid: str
    isolation: str = IsolationLevel.SCOPE
    payload: Dict[str, Any] = field(default_factory=dict)

@runtime_checkable
class IRuntimeScheduler(Protocol):
    """运行时调度中枢接口"""
    def spawn(self, artifact: Any, isolation: str = IsolationLevel.NONE) -> str: ...
    def dispatch(self, request: ExecutionRequest, execution_context: IExecutionContext) -> ExecutionSignal: ...
    def snapshot(self, instance_id: str) -> Dict[str, Any]: ...
    def restore(self, instance_id: str, snapshot: Dict[str, Any]) -> None: ...
    def terminate(self, instance_id: str) -> None: ...

@runtime_checkable
class ServiceContext(Protocol):
    """注入容器，聚合所有运行时服务"""
    @property
    def registry(self) -> Any: ...
    @property
    def issue_tracker(self) -> IssueTracker: ...
    @property
    def llm_executor(self) -> LLMExecutor: ...
    @property
    def module_manager(self) -> ModuleManager: ...
    @property
    def object_factory(self) -> IObjectFactory: ...
    @property
    def interop(self) -> InterOp: ...
    @property
    def permission_manager(self) -> PermissionManager: ...
    @property
    def host_service(self) -> Optional[IHostService]: ...
    @property
    def source_provider(self) -> Optional[ISourceProvider]: ...
    @property
    def orchestrator(self) -> Optional[IKernelOrchestrator]: ...
    @property
    def debugger(self) -> Any: ...
    @property
    def scheduler(self) -> Optional[IRuntimeScheduler]: ...
    @property
    def capability_registry(self) -> Any: ...

@runtime_checkable
class IModuleLoader(Protocol):
    """模块加载器接口 (ModuleLoader)"""
    def load_and_register_all(self, context: ServiceContext, execution_context: IExecutionContext) -> None: ...

class Interpreter(Protocol):
    """IBC-Inter 解释器协议"""
    @property
    def runtime_context(self) -> RuntimeContext: ...
    @property
    def registry(self) -> Any: ...
    @property
    def symbol_view(self) -> SymbolView: ...
    def visit(self, node_uid: str) -> Any: ...
    def get_node_data(self, node_uid: str) -> Mapping[str, Any]: ...
    def get_side_table(self, table_name: str, key: str) -> Any: ...
    def execute_module(self, root_node_uid: str, module_name: str, scope: Any): ...
    def sync_state(self, parent_context: RuntimeContext, policy: Dict[str, Any]): ...
