from typing import Any, Protocol, List, Dict, Callable, Optional, Type, Union, runtime_checkable, Mapping, TYPE_CHECKING, Tuple
if TYPE_CHECKING:
    from core.kernel import ast as ast

from core.base.interfaces import (
    IssueTracker, ISourceProvider, ICompilerService
)

from core.kernel.interfaces import IExecutionContext, IModuleScope

@runtime_checkable
class IStackInspector(Protocol):
    """提供对调用栈和意图栈的内省能力"""
    def get_call_stack_depth(self) -> int: ...
    def get_active_intents(self) -> List[str]: ...
    def get_instruction_count(self) -> int: ...
    def get_captured_intents(self, obj: Any) -> List[str]: ...
    def get_current_script_path(self) -> Optional[str]: ...
    def get_current_script_dir(self) -> Optional[str]: ...

@runtime_checkable
class Registry(Protocol):
    """类与实例注册表接口"""
    def get_class(self, name: str) -> Any: ...
    def box(self, value: Any, memo: Optional[Dict[int, Any]] = None) -> Any: ...

class RuntimeSymbol(Protocol):
    """运行时符号，包含值和类型信息"""
    name: str
    value: Any
    declared_type: Any
    current_type: Any
    is_const: bool
    is_intrinsic: bool  # 内置函数（intrinsic）符号标志，由 IntrinsicManager 注入

class SymbolView(Protocol):
    """只读符号视图接口"""
    def get(self, name: str) -> Any: ...
    def get_symbol(self, name: str) -> Optional[RuntimeSymbol]: ...
    def has(self, name: str) -> bool: ...

class Scope(Protocol):
    """运行时作用域接口"""
    def define(self, name: str, value: Any, declared_type: Any = None, is_const: bool = False, uid: Optional[str] = None, force: bool = False, is_intrinsic: bool = False) -> None: ...
    def assign(self, name: str, value: Any) -> bool: ...
    def get(self, name: str) -> Any: ...
    def get_symbol(self, name: str) -> Optional[RuntimeSymbol]: ...
    def get_all_symbols(self) -> Dict[str, RuntimeSymbol]: ...
    @property
    def parent(self) -> Optional['Scope']: ...
    def iter_cells(self) -> Any:
        """
        枚举本作用域（不递归父）已提升为 IbCell 的变量条目（根集合扫描入口）。
        默认实现返回空迭代器；具体作用域类型若支持 Cell 提升应覆写此方法。
        """
        return iter(())
    def is_cell_promoted(self, sym_uid: str) -> bool:
        """判断 sym_uid 是否已提升为 Cell 变量（封装替代私有 _cell_map 探测）。

        默认返回 False；支持 Cell 提升的 ScopeImpl 应覆写此方法。
        """
        return False
    def define_raw(self, name: Optional[str], value: Any, uid: Optional[str] = None, declared_type: Any = None) -> Any:
        """低级符号写入，绕过类型检查（VM 特殊路径专用）。

        默认实现委托到 define()；支持 LLMFuture 占位符写入的 ScopeImpl 应覆写此方法。
        """
        self.define(name or "", value, uid=uid)
        return None
    def assign_by_uid(self, uid: str, value: Any, skip_type_check: bool = False) -> bool:
        """基于 UID 的赋值（向上查找父作用域）。

        默认实现返回 False（不支持 UID 映射时安全降级）；
        支持 UID 映射的 ScopeImpl 应覆写此方法。
        """
        return False
    def get_symbol_by_uid(self, uid: str) -> Optional[RuntimeSymbol]:
        """向上查找 UID 符号。

        默认实现返回 None；支持 UID 映射的 ScopeImpl 应覆写此方法。
        """
        return None
    def get_all_symbols_by_uid(self) -> Dict[str, RuntimeSymbol]:
        """枚举本作用域（不递归父）的所有 UID → 符号映射。

        序列化/快照恢复的公开枚举接口（替代私有 ``_uid_to_symbol`` 探测）。
        默认实现返回空字典；支持 UID 映射的 ScopeImpl 应覆写此方法。
        """
        return {}
    def bind_symbol_by_uid(self, uid: str, sym: RuntimeSymbol) -> None:
        """将既有符号对象绑定到指定 UID（反序列化恢复路径）。

        默认实现为 no-op；支持 UID 映射的 ScopeImpl 应覆写此方法。
        """
        ...
    def promote_to_cell(self, sym_uid: str) -> Optional[Any]:
        """将符号提升为 Cell 变量（公理 SC-3），返回 IbCell 或 None。

        默认实现返回 None；支持 Cell 提升的 ScopeImpl 应覆写此方法。
        """
        return None
    @property
    def registry(self) -> Any:
        """本作用域关联的对象注册表。"""
        ...

class RuntimeContext(Protocol):
    """解释器运行时上下文，管理作用域和意图栈"""
    def enter_scope(self) -> None: ...
    def exit_scope(self) -> None: ...
    def define_variable(self, name: str, value: Any, declared_type: Any = None, is_const: bool = False, uid: Optional[str] = None, force: bool = False, is_intrinsic: bool = False) -> None: ...
    def set_variable(self, name: str, value: Any) -> None: ...
    def get_variable(self, name: str) -> Any: ...
    def get_symbol(self, name: str) -> Optional[RuntimeSymbol]: ...
    def get_vars(self) -> Dict[str, Any]: ...

    def set_global_intent(self, intent: 'IbIntent') -> None: ...
    def clear_global_intents(self) -> None: ...
    def remove_global_intent(self, intent: Union[str, 'IbIntent']) -> None: ...
    def get_global_intents(self) -> List['IbIntent']: ...

    def push_intent(self, intent: Union[str, 'IbIntent'], mode: str = "+", tag: Optional[str] = None) -> None: ...
    def pop_intent(self) -> Optional['IbIntent']: ...
    def get_active_intents(self) -> List['IbIntent']: ...
    def add_smear_intent(self, intent: 'IbIntent') -> None: ...
    def get_resolved_prompt_intents(self, execution_context: IExecutionContext, call_intent: Optional['IbIntent'] = None) -> List[str]: ...

    def fork_intent_snapshot(self) -> Any: ...
    def get_active_intent_ibobj(self) -> Any: ...
    def set_active_intent_ibobj(self, ibobj: Any) -> None: ...
    def clear_inherited_intents(self) -> None: ...
    def restore_active_intents(self, intents: Any) -> None: ...
    def enter_intent_scope(self) -> tuple: ...
    def exit_intent_scope(self, saved: tuple) -> None: ...
    def replace_intent_context(self, new_ctx: Any) -> None: ...

    @property
    def intent_context(self) -> Any: ...

    @property
    def intent_stack(self) -> List['ast.IbIntentInfo']: ...

    def push_loop_context(self, index: int, total: int) -> None: ...
    def pop_loop_context(self) -> None: ...
    def get_loop_context(self) -> Optional[Dict[str, int]]: ...
    def get_loop_context_stack(self) -> List[Dict[str, int]]:
        """返回当前循环上下文栈的深拷贝快照（llmexcept 帧保存用）。

        默认实现返回空列表；RuntimeContextImpl 应覆写此方法。
        """
        return []
    def restore_loop_context_stack(self, stack: List[Dict[str, int]]) -> None:
        """以快照整体替换循环上下文栈（llmexcept 帧恢复用）。

        默认实现为 no-op；RuntimeContextImpl 应覆写此方法。
        """
        ...

    @property
    def current_scope(self) -> Scope: ...
    @property
    def global_scope(self) -> Scope: ...

    @property
    def registry(self) -> Any: ...

    def get_symbol_view(self) -> SymbolView: ...

class LLMExecutor(Protocol):
    """LLM 执行组件，负责构建 Prompt 并调用 LLM"""
    def execute_llm_function(self, node_uid: str, execution_context: IExecutionContext) -> Any: ...
    def execute_behavior_expression(self, node_uid: str, execution_context: IExecutionContext, captured_intents: Optional[List[str]] = None) -> Any: ...
    def get_current_call_info(self) -> Mapping[str, Any]: ...
    def resolve(self, node_uid: str) -> Any:
        """阻塞等待 ``node_uid`` 对应的 ``LLMFuture`` 完成，返回结果。"""
        ...
    def dispatch_eager(
        self,
        node_uid: str,
        execution_context: IExecutionContext,
        intent_ctx: Optional[Any] = None,
    ) -> Any:
        """立即将 LLM 调用提交到后台线程池，返回 ``LLMFuture``（非阻塞）。"""
        ...
    def hydrate(self, service_context: Any) -> None:
        """水化依赖（注入 ``ServiceContext`` 并初始化结果解析器）。"""
        ...
    def run_batch(self, behavior: Any, items: List[Any], execution_context: IExecutionContext) -> List[Any]:
        """并发批量执行行为对象，保序返回结果列表。"""
        ...

class InterOp(Protocol):
    """Python 互操作组件，负责 Python 函数/类的映射和命名空间隔离"""
    @property
    def metadata(self) -> Any: ... # Returns MetadataRegistry

    def register_package(self, name: str, obj: Any, metadata: Optional[Any] = None, discovery_name: Optional[str] = None) -> None: ...
    def get_package(self, name: str) -> Optional[Any]: ...
    def bind_native_contract(self, module_name: str, vtable: Dict[str, Any], whitelist: List[str]) -> None: ...
    def get_native_contract(self, module_name: str) -> Optional[Tuple[Dict[str, Any], List[str]]]: ...
    def get_discovery_name(self, module_name: str) -> Optional[str]: ...
    def get_module_name_by_discovery(self, discovery_name: str) -> Optional[str]: ...
    def get_all_package_names(self) -> List[str]: ...
    def wrap_python_function(self, func: Callable) -> Callable: ...

class ModuleManager(Protocol):
    """模块管理组件，负责 import 逻辑"""
    def import_module(self, module_name: str, execution_context: IExecutionContext) -> Any: ...
    def import_from(self, module_name: str, names: List[tuple], execution_context: IExecutionContext) -> None: ...

class ModuleInstance(Protocol):
    """IBC-Inter 模块实例，表示一个已执行模块的运行时状态"""
    name: str
    scope: Scope
    def get_variable(self, name: str) -> Any: ...

class PermissionManager(Protocol):
    """权限管理组件，负责沙箱路径校验"""
    @property
    def root_dir(self) -> str: ...
    def validate_path(self, path: str, operation: str = "access") -> None: ...
    def enable_external_access(self) -> None: ...
    def is_external_access_enabled(self) -> bool: ...

class IKernelOrchestrator(Protocol):
    """
     内核协调器协议。
    定义了运行时环境向引擎层（Host/Engine）发起的最高特权系统调用。
    用于解决架构穿透问题，使运行时无需感知 Compiler 等底层构建组件。
    """
    def request_spawn_isolated(self, entry_path: str, policy: Dict[str, Any]) -> str: ...
    def request_collect(self, handle: str) -> Dict[str, Any]: ...
    def is_spawn_done(self, handle: str) -> bool: ...

class IHostService(Protocol):
    """内核级宿主服务子系统接口"""
    def save_state(self, path: str) -> None: ...
    def load_state(self, path: str) -> None: ...
    def run_isolated(self, path: str, policy: Dict[str, Any]) -> "HostAwaitable": ...
    def spawn_isolated(self, path: str, policy: Dict[str, Any]) -> str: ...
    def collect(self, handle: str) -> "HostAwaitable": ...
    def get_source(self) -> str: ...
    @property
    def orchestrator(self) -> Optional[IKernelOrchestrator]: ...

class IInterpreterFactory(Protocol):
    """
    解释器实例工厂接口。
    用于解决 HostService 与 Interpreter 之间的物理循环依赖。
    """
    def spawn_interpreter(self,
                          artifact: Any,
                          registry: Any,
                          host_interface: Any,
                          root_dir: str,
                          parent_context: RuntimeContext) -> 'Interpreter': ...

    def create_compiler(self, root_dir: str, host_interface: Any, registry: Any) -> ICompilerService: ...

@runtime_checkable
class IIbObject(Protocol):
    """IBC-Inter 对象基础协议 (Everything is an Object)"""
    @property
    def ib_class(self) -> 'IIbClass': ...
    @property
    def fields(self) -> Mapping[str, Any]: ...
    def receive(self, message: str, args: List['IIbObject']) -> 'IIbObject': ...
    def to_native(self, memo: Optional[Dict[int, Any]] = None) -> Any: ...
    def __to_prompt__(self) -> str: ...
    def __from_prompt__(self, raw_response: str) -> Tuple[bool, Any]:
        """
        从 LLM 返回的原始文本中解析值。

        Returns:
            (True, parsed_value) - 解析成功
            (False, retry_hint)  - 解析失败，retry_hint 用于提示重试方向
        """
        ...
    def __outputhint_prompt__(self) -> str:
        """
        返回期望的 LLM 输出格式描述。
        用于提示词注入，告诉 LLM 应该输出什么格式。
        """
        ...

@runtime_checkable
class IIbClass(IIbObject, Protocol):
    """IBC-Inter 类/元对象协议"""
    name: str
    parent: Optional['IIbClass']
    registry: Any
    def lookup_method(self, name: str) -> Optional['IIbFunction']: ...
    def register_method(self, name: str, method: 'IIbFunction') -> None: ...
    def instantiate(self, args: List['IIbObject'], context: Optional[IExecutionContext] = None) -> 'IIbObject': ...

@runtime_checkable
class IIbFunction(IIbObject, Protocol):
    """IBC-Inter 可调用对象协议"""
    def call(self, receiver: 'IIbObject', args: List['IIbObject']) -> 'IIbObject': ...

@runtime_checkable
class IIbList(IIbObject, Protocol):
    """IBC-Inter 列表对象协议"""
    elements: List['IIbObject']
    def append(self, item: 'IIbObject') -> 'IIbObject': ...
    def pop(self) -> 'IIbObject': ...
    def len(self) -> 'IIbObject': ...

@runtime_checkable
class IIbIntent(IIbObject, Protocol):
    """IBC-Inter 意图对象协议"""
    content: str
    mode: Any
    tag: Optional[str]
    role: Any
    def resolve_content(self, context: RuntimeContext, execution_context: IExecutionContext) -> str: ...

@runtime_checkable
class IIbBehavior(IIbObject, Protocol):
    """延迟执行的行为对象协议 (~...~)

    ``captured_intents``:
      - ``None``：lambda 模式（调用时使用当前上下文意图栈）
      - ``IbIntentContext`` 实例：snapshot 模式 / dispatch_eager（已 fork 的值快照）
    """
    node: str
    captured_intents: Optional[Any]  # Optional[IbIntentContext]; Any 避免循环导入
    expected_type: Optional[str]

@runtime_checkable
class IIbModule(IIbObject, Protocol):
    """IBC-Inter 模块对象协议"""
    name: str
    scope: 'IModuleScope'

class IObjectFactory(Protocol):
    """
    运行时对象工厂接口。
    用于解耦 Service（如 ModuleManager）与具体运行时对象（如 IbModule）的构造。
    """
    def create_module(self, name: str, scope: 'IModuleScope') -> 'IIbModule': ...
    def create_scope(self, parent: Optional['Scope'] = None) -> 'Scope': ...
    def create_native_object(self, py_obj: Any, ib_class: 'IIbClass', vtable: Optional[Dict[str, Any]] = None, whitelist: Optional[List[str]] = None) -> 'IIbObject': ...
    def create_behavior(self, node_uid: str, captured_intents: List[Any], expected_type: Optional[str] = None, call_intent: Optional[Any] = None, capture_mode: Optional[str] = None, execution_context: Optional[Any] = None, params_uids: Optional[List[str]] = None, closure: Optional[Dict[str, Any]] = None) -> Any: ...
    def create_fn_callable(self, node_uid: str, capture_mode: str = "lambda", execution_context: Optional[Any] = None, params_uids: Optional[List[str]] = None, body_uid: Optional[str] = None, closure: Optional[Dict[str, Any]] = None) -> Any: ...
    def create_list(self, elements: List['IIbObject']) -> 'IIbList': ...
    def create_intent(self, content: str = "", mode: Any = None, tag: Optional[str] = None, role: Any = None) -> 'IIbIntent': ...
    def create_intent_from_node(self, node_uid: str, node_data: Mapping[str, Any], role: Any = None) -> 'IIbIntent': ...
    def create_context(self, initial_scope: Optional['Scope'] = None) -> 'RuntimeContext': ...
    def create_runtime_symbol(self, name: str, value: Any, declared_type: Any = None, is_const: bool = False) -> 'RuntimeSymbol': ...

    def register_llm_executor_factory(self, factory: Callable) -> None: ...
    def create_llm_executor(self, service_context: 'ServiceContext', execution_context: IExecutionContext) -> 'LLMExecutor': ...

@runtime_checkable
class IStateProvider(Protocol):
    """提供运行时状态的只读镜像，用于解耦序列化逻辑"""
    def get_current_scope(self) -> Scope: ...
    def get_global_intents(self) -> List[Any]: ...
    def get_active_intents(self) -> List[Any]: ...

@runtime_checkable
class IRuntimeScheduler(Protocol):
    """运行时调度中枢接口"""
    def spawn(self, artifact: Any) -> str: ...
    def snapshot(self, instance_id: str) -> Dict[str, Any]: ...
    def restore(self, instance_id: str, snapshot: Dict[str, Any]) -> None: ...
    def terminate(self, instance_id: str) -> None: ...

@runtime_checkable
class ServiceContext(Protocol):
    """注入容器，聚合所有运行时服务"""
    @property
    def registry(self) -> Any: ...
    @property
    def issue_tracker(self) -> IssueTracker: ...
    @property
    def llm_executor(self) -> LLMExecutor: ...
    @property
    def module_manager(self) -> ModuleManager: ...
    @property
    def object_factory(self) -> IObjectFactory: ...
    @property
    def interop(self) -> InterOp: ...
    @property
    def permission_manager(self) -> PermissionManager: ...
    @property
    def host_service(self) -> Optional[IHostService]: ...
    @property
    def source_provider(self) -> Optional[ISourceProvider]: ...
    @property
    def orchestrator(self) -> Optional[IKernelOrchestrator]: ...
    @property
    def debugger(self) -> Any: ...
    @property
    def scheduler(self) -> Optional[IRuntimeScheduler]: ...
    @property
    def capability_registry(self) -> Any: ...
    @property
    def interpreter(self) -> Optional['Interpreter']: ...

@runtime_checkable
class IModuleLoader(Protocol):
    """模块加载器接口 (ModuleLoader)"""
    def load_and_register_all(self, context: ServiceContext, execution_context: IExecutionContext) -> None: ...

class Interpreter(Protocol):
    """IBC-Inter 解释器协议"""
    @property
    def runtime_context(self) -> RuntimeContext: ...
    @property
    def registry(self) -> Any: ...
    @property
    def symbol_view(self) -> SymbolView: ...
    def get_node_data(self, node_uid: str) -> Mapping[str, Any]: ...
    def get_side_table(self, table_name: str, key: str) -> Any: ...
    def execute_module(self, root_node_uid: str, module_name: str, scope: Any): ...
