from typing import Any, Protocol, List, Dict, Callable, Optional
from dataclasses import dataclass
from typedef import parser_types as ast

# 定义解释器上下文协议
class InterpreterContext(Protocol):
    def get_variable(self, name: str) -> Any: ...
    def set_variable(self, name: str, value: Any) -> None: ...
    def define_variable(self, name: str, value: Any) -> None: ...
    def call_function(self, func_name: str, args: List[Any]) -> Any: ...
    def register_function(self, name: str, func: Callable) -> None: ...
    def register_type(self, name: str, type_cls: Any) -> None: ...
    def register_operator_handler(self, handler: 'OperatorHandler') -> None: ...
    def print_output(self, message: str) -> None: ...
    
    @property
    def current_scope(self) -> Any: ...

# 定义模块接口协议
class IBCModule(Protocol):
    def register(self, context: InterpreterContext) -> None:
        """
        在模块加载时调用，用于向解释器注册函数、类型或变量。
        """
        ...

# 定义运算符处理协议（可选，用于未来的运算符重载）
class OperatorHandler(Protocol):
    def apply_binop(self, op: str, left: Any, right: Any) -> Any: ...
    def apply_unary(self, op: str, operand: Any) -> Any: ...
