from typing import Any, Protocol, List, Dict, Callable, Optional, Type, Union, runtime_checkable
from core.types import parser_types as ast

# --- Diagnostics ---

@runtime_checkable
class IssueTracker(Protocol):
    """诊断管理器接口"""
    def report(self, severity: Any, code: str, message: str, 
               location: Optional[Any] = None, hint: Optional[str] = None) -> None: ...
    def has_errors(self) -> bool: ...

# --- Runtime Value Symbols ---

class RuntimeSymbol(Protocol):
    """运行时符号，包含值和类型信息"""
    name: str
    value: Any
    declared_type: Any  # IBC-Inter 类型 (int, float, str, list, dict, var, etc.)
    current_type: Any   # 运行时实际类型
    is_const: bool      # 是否为常量（内置函数等）

# --- Scope & Context ---

class Scope(Protocol):
    """运行时作用域接口"""
    def define(self, name: str, value: Any, declared_type: Any = None, is_const: bool = False) -> None: ...
    def assign(self, name: str, value: Any) -> bool: ...
    def get(self, name: str) -> Any: ...
    def get_symbol(self, name: str) -> Optional[RuntimeSymbol]: ...
    def get_all_symbols(self) -> Dict[str, RuntimeSymbol]: ...
    @property
    def parent(self) -> Optional['Scope']: ...

class RuntimeContext(Protocol):
    """解释器运行时上下文，管理作用域和意图栈"""
    def enter_scope(self) -> None: ...
    def exit_scope(self) -> None: ...
    def get_variable(self, name: str) -> Any: ...
    def get_symbol(self, name: str) -> Optional[RuntimeSymbol]: ...
    def set_variable(self, name: str, value: Any) -> None: ...
    def define_variable(self, name: str, value: Any, declared_type: Any = None, is_const: bool = False) -> None: ...
    
    # 意图管理 (三层架构: Global, Block, Call)
    def set_global_intent(self, intent: str) -> None: ...
    def clear_global_intents(self) -> None: ...
    def remove_global_intent(self, intent: str) -> None: ...
    def get_global_intents(self) -> List[str]: ...
    
    # 意图屏蔽控制 (Block 级别)
    def enter_intent_exclusive_scope(self) -> None: ...
    def exit_intent_exclusive_scope(self) -> None: ...
    def is_intent_exclusive(self) -> bool: ...
    
    def push_intent(self, intent: 'ast.IntentInfo') -> None: ...
    def pop_intent(self) -> Optional['ast.IntentInfo']: ...
    def get_active_intents(self) -> List['ast.IntentInfo']: ...
    
    # 意图合并逻辑由 LLMExecutor 实现，但 Context 需提供数据支撑
    
    @property
    def current_scope(self) -> Scope: ...
    @property
    def global_scope(self) -> Scope: ...

# --- Components ---

class LLMExecutor(Protocol):
    """LLM 执行组件，负责构建 Prompt 并调用 LLM"""
    def execute_llm_function(self, node: ast.LLMFunctionDef, args: List[Any], context: 'RuntimeContext') -> str: ...
    def execute_behavior_expression(self, node: ast.BehaviorExpr, context: 'RuntimeContext') -> str: ...

class InterOp(Protocol):
    """Python 互操作组件，负责 Python 函数/类的映射和命名空间隔离"""
    def register_package(self, name: str, obj: Any) -> None: ...
    def get_package(self, name: str) -> Optional[Any]: ...
    def wrap_python_function(self, func: Callable) -> Callable: ...

class ModuleManager(Protocol):
    """模块管理组件，负责 import 逻辑"""
    def import_module(self, module_name: str, context: 'RuntimeContext') -> None: ...
    def import_from(self, module_name: str, names: List[str], context: 'RuntimeContext') -> None: ...

class Evaluator(Protocol):
    """运算器组件，负责处理表达式运算符"""
    def evaluate_expr(self, node: ast.ASTNode, context: 'RuntimeContext') -> Any: ...
    def evaluate_binop(self, op: str, left: Any, right: Any, node: Optional[ast.ASTNode] = None) -> Any: ...
    def evaluate_unary(self, op: str, operand: Any, node: Optional[ast.ASTNode] = None) -> Any: ...
    def evaluate_assign(self, target: ast.ASTNode, value: Any, context: 'RuntimeContext') -> None: ...

class ModuleInstance(Protocol):
    """IBC-Inter 模块实例，表示一个已执行模块的运行时状态"""
    name: str
    scope: Scope
    def get_variable(self, name: str) -> Any: ...

class PermissionManager(Protocol):
    """权限管理组件，负责沙箱路径校验"""
    def validate_path(self, path: str, operation: str = "access") -> None: ...
    def enable_external_access(self) -> None: ...
    def is_external_access_enabled(self) -> bool: ...

# --- Service Context ---

class ServiceContext(Protocol):
    """注入容器，聚合所有运行时服务"""
    @property
    def interpreter(self) -> 'Interpreter': ...
    @property
    def issue_tracker(self) -> IssueTracker: ...
    @property
    def runtime_context(self) -> RuntimeContext: ...
    @property
    def evaluator(self) -> Evaluator: ...
    @property
    def llm_executor(self) -> LLMExecutor: ...
    @property
    def module_manager(self) -> ModuleManager: ...
    @property
    def interop(self) -> InterOp: ...
    @property
    def permission_manager(self) -> PermissionManager: ...

# --- Main Interpreter ---

class Interpreter(Protocol):
    """解释器主接口 (Visitor)"""
    def visit(self, node: ast.ASTNode) -> Any: ...
    def interpret(self, module: ast.Module) -> Any: ...
    def print_output(self, message: str) -> None: ...
