from typing import Any, Protocol, Optional, List, Dict, Union, Mapping, runtime_checkable

__all__ = [
    "ISourceProvider",
    "ICompilerService",
    "IssueTracker",
    "IStateReader",
    "ISymbolView",
    "ILLMProvider",
    "ILLMExecutor",
    "IIntentManager",
]

@runtime_checkable
class ISourceProvider(Protocol):
    """
    源码提供者接口。支持"无盘化"诊断，从内存缓冲区获取代码片段。
    """
    def get_line(self, file_path: str, lineno: int) -> Optional[str]: ...
    def get_full_source(self, file_path: str) -> Optional[str]: ...

@runtime_checkable
class ICompilerService(Protocol):
    """
    编译器服务接口。允许运行时动态编译代码或查询模块信息。
    """
    def compile_file(self, file_path: str) -> Any: ...
    def resolve_module_path(self, module_name: str) -> Optional[str]: ...
    def get_module_source(self, module_name: str) -> Optional[str]: ...

@runtime_checkable
class IssueTracker(Protocol):
    """诊断管理器接口"""
    def report(self, severity: Any, code: str, message: str,
               location: Optional[Any] = None, hint: Optional[str] = None) -> None: ...
    def has_errors(self) -> bool: ...

@runtime_checkable
class IStateReader(Protocol):
    """提供对解释器运行时状态（如变量）的只读访问"""
    def get_vars_snapshot(self) -> Dict[str, Any]: ...

@runtime_checkable
class ISymbolView(Protocol):
    """只读符号视图接口"""
    def get(self, name: str) -> Any: ...
    def get_symbol(self, name: str) -> Optional[Any]: ...
    def has(self, name: str) -> bool: ...

@runtime_checkable
class ILLMProvider(Protocol):
    """LLM 服务提供者标准接口"""
    def __call__(self, sys_prompt: str, user_prompt: str, scene: str = "general") -> str: ...
    def get_last_call_info(self) -> Dict[str, Any]: ...
    def set_retry_hint(self, hint: str) -> None: ...
    def get_retry_prompt(self, node_type: str) -> Optional[str]: ...

@runtime_checkable
class ILLMExecutor(Protocol):
    """提供对内核 LLM 执行器的内省能力"""
    def get_last_call_info(self) -> Dict[str, Any]: ...

@runtime_checkable
class IIntentManager(Protocol):
    """提供对意图（Global, Block）的管理能力"""
    def set_global_intent(self, intent: Union[str, Any]) -> None: ...
    def clear_global_intents(self) -> None: ...
    def remove_global_intent(self, intent: Union[str, Any]) -> None: ...
    def get_global_intents(self) -> List[Any]: ...
    def get_active_intents(self) -> List[Any]: ...
    def push_intent(self, intent: Union[str, Any], mode: str = "+", tag: Optional[str] = None) -> None: ...
