from typing import Any, Protocol, Optional, List, Mapping, runtime_checkable

__all__ = ["IExecutionContext"]

@runtime_checkable
class IExecutionContext(Protocol):
    """
    运行时执行上下文数据协议。
    作为 Interpreter 与底层组件（Kernel/Foundation）解耦的桥梁。
    它仅包含执行所需的只读数据池、栈内省能力以及求值入口。

    此接口定义在 kernel 层，作为架构核心抽象。
    runtime 层实现具体类并实现此接口。
    """
    @property
    def node_pool(self) -> Mapping[str, Any]: ...

    @property
    def symbol_pool(self) -> Mapping[str, Any]: ...

    @property
    def scope_pool(self) -> Mapping[str, Any]: ...

    @property
    def type_pool(self) -> Mapping[str, Any]: ...

    @property
    def asset_pool(self) -> Mapping[str, str]: ...

    @property
    def stack_inspector(self) -> Any: ...

    @property
    def registry(self) -> Any: ...

    @property
    def factory(self) -> Any: ...

    @property
    def runtime_context(self) -> Any: ...

    @property
    def module_manager(self) -> Any: ...

    @property
    def current_module_name(self) -> Optional[str]: ...

    @current_module_name.setter
    def current_module_name(self, value: Optional[str]) -> None: ...

    @property
    def strict_mode(self) -> bool: ...

    def visit(self, node_uid: str, module_name: Optional[str] = None, bypass_protection: bool = False) -> Any: ...

    def get_node_data(self, node_uid: str) -> Mapping[str, Any]: ...

    def get_side_table(self, table_name: str, key: str) -> Any: ...

    def push_stack(self, name: str, location: Optional[Any] = None, is_user_function: bool = False, **kwargs) -> None: ...

    def pop_stack(self) -> None: ...

    def resolve_type_from_symbol(self, sym_uid: str) -> Optional[Any]: ...

    def extract_name_id(self, node_uid: str) -> Optional[str]: ...

    def resolve_value(self, val: Any) -> Any: ...

    def is_truthy(self, value: Any) -> bool: ...