"""
诊断码注册表。

每个码的常量名即为其值（常量名 = 字符串值 = 单点真理）。
新增码时取一个描述性名称即可，无需分配编号。
按域分组，每组以注释行分隔。
"""

# === 词法 (LEX_) ===
LEX_INVALID_CHAR = "LEX_INVALID_CHAR"
LEX_UNTERMINATED_STRING = "LEX_UNTERMINATED_STRING"
LEX_UNTERMINATED_BLOCK = "LEX_UNTERMINATED_BLOCK"
LEX_INVALID_NUMBER = "LEX_INVALID_NUMBER"
LEX_INVALID_ESCAPE = "LEX_INVALID_ESCAPE"
LEX_UNTERMINATED_BEHAVIOR = "LEX_UNTERMINATED_BEHAVIOR"

# === 语法 (PAR_) ===
PAR_EXPECTED_TOKEN = "PAR_EXPECTED_TOKEN"
PAR_UNEXPECTED_TOKEN = "PAR_UNEXPECTED_TOKEN"
PAR_INVALID_SYNTAX = "PAR_INVALID_SYNTAX"
PAR_UNEXPECTED_EOF = "PAR_UNEXPECTED_EOF"
PAR_INDENTATION_ERROR = "PAR_INDENTATION_ERROR"
PAR_MULTIPLE_INTENTS = "PAR_MULTIPLE_INTENTS"
PAR_DEPRECATED_CAST_SYNTAX = "PAR_DEPRECATED_CAST_SYNTAX"
PAR_POSITIONAL_AFTER_KEYWORD = "PAR_POSITIONAL_AFTER_KEYWORD"

# === 语义 (SEM_) ===
# -- 符号解析 --
SEM_UNDEFINED_SYMBOL = "SEM_UNDEFINED_SYMBOL"
SEM_REDEFINITION = "SEM_REDEFINITION"
SEM_IMPORT_CONFLICT = "SEM_IMPORT_CONFLICT"
# -- 类型系统 --
SEM_TYPE_MISMATCH = "SEM_TYPE_MISMATCH"
SEM_ARG_COUNT_MISMATCH = "SEM_ARG_COUNT_MISMATCH"
SEM_DUAL_ASSIGNABLE = "SEM_DUAL_ASSIGNABLE"
SEM_CAST_NO_CONVERTER = "SEM_CAST_NO_CONVERTER"
SEM_CONTAINER_METHOD_HINT = "SEM_CONTAINER_METHOD_HINT"
SEM_PROTOCOL_SIGNATURE = "SEM_PROTOCOL_SIGNATURE"
SEM_SUPER_OUTSIDE_METHOD = "SEM_SUPER_OUTSIDE_METHOD"
SEM_UNRESOLVED_TYPE = "SEM_UNRESOLVED_TYPE"
# -- 函数参数绑定 --
SEM_DUPLICATE_KEYWORD = "SEM_DUPLICATE_KEYWORD"
SEM_UNKNOWN_KEYWORD = "SEM_UNKNOWN_KEYWORD"
SEM_MISSING_REQUIRED_ARG = "SEM_MISSING_REQUIRED_ARG"
SEM_DEFAULT_TYPE_MISMATCH = "SEM_DEFAULT_TYPE_MISMATCH"
SEM_TOO_MANY_POSITIONAL = "SEM_TOO_MANY_POSITIONAL"
SEM_MISSING_RETURN_ANNOTATION = "SEM_MISSING_RETURN_ANNOTATION"
SEM_MULTI_TYPE_LIST_REMOVED = "SEM_MULTI_TYPE_LIST_REMOVED"
# -- 作用域 --
SEM_INVALID_SCOPE = "SEM_INVALID_SCOPE"
SEM_NONLOCAL_NOT_FOUND = "SEM_NONLOCAL_NOT_FOUND"
# -- 意图系统 --
SEM_INTENT_PLACEMENT = "SEM_INTENT_PLACEMENT"
SEM_INTENT_STATIC_CALL = "SEM_INTENT_STATIC_CALL"
# -- LLM 输出契约 --
SEM_BEHAVIOR_OUTPUT_NOT_PARSEABLE = "SEM_BEHAVIOR_OUTPUT_NOT_PARSEABLE"
# -- 隔离与快照 --
SEM_LLMEXCEPT_BODY_WRITE = "SEM_LLMEXCEPT_BODY_WRITE"
SEM_LLMEXCEPT_BINDING = "SEM_LLMEXCEPT_BINDING"
SEM_LLMEXCEPT_SCOPE_BINDING = "SEM_LLMEXCEPT_SCOPE_BINDING"
SEM_LLMEXCEPT_MUTATING_CALL = "SEM_LLMEXCEPT_MUTATING_CALL"
SEM_LLMEXCEPT_FILE_WRITE = "SEM_LLMEXCEPT_FILE_WRITE"
# -- 特殊 --
SEM_UNCATEGORIZED = "SEM_UNCATEGORIZED"
SEM_INTERNAL_SENTINEL = "SEM_INTERNAL_SENTINEL"

# === 依赖 (DEP_) ===
DEP_MODULE_NOT_FOUND = "DEP_MODULE_NOT_FOUND"
DEP_FILE_NOT_FOUND = "DEP_FILE_NOT_FOUND"
DEP_INVALID_IMPORT_POSITION = "DEP_INVALID_IMPORT_POSITION"
DEP_GRAPH_ERROR = "DEP_GRAPH_ERROR"
DEP_FAILED_DEPENDENCY = "DEP_FAILED_DEPENDENCY"
DEP_SECURITY_ERROR = "DEP_SECURITY_ERROR"
DEP_CIRCULAR_IMPORT = "DEP_CIRCULAR_IMPORT"

# === 内部 (INT_) ===
INT_INTERNAL_ERROR = "INT_INTERNAL_ERROR"
ICE_TYPE_LEAK = "ICE_TYPE_LEAK"

# === 运行时 (RUN_) ===
RUN_GENERIC_ERROR = "RUN_GENERIC_ERROR"
RUN_TYPE_MISMATCH = "RUN_TYPE_MISMATCH"
RUN_UNDEFINED_VARIABLE = "RUN_UNDEFINED_VARIABLE"
RUN_DIVISION_BY_ZERO = "RUN_DIVISION_BY_ZERO"
RUN_ATTRIBUTE_ERROR = "RUN_ATTRIBUTE_ERROR"
RUN_INDEX_ERROR = "RUN_INDEX_ERROR"
RUN_CALL_ERROR = "RUN_CALL_ERROR"
RUN_LIMIT_EXCEEDED = "RUN_LIMIT_EXCEEDED"
RUN_LLM_ERROR = "RUN_LLM_ERROR"
RUN_PERMISSION_ERROR = "RUN_PERMISSION_ERROR"
RUN_LLMEXCEPT_SNAPSHOT_VIOLATION = "RUN_LLMEXCEPT_SNAPSHOT_VIOLATION"
