from core.extension.spec_builder import SpecBuilder

metadata = (
    SpecBuilder("ai")
    .func("set_config", ["str", "str", "str"], "void")
    .func("set_retry_hint", ["str"], "void")
    .func("set_retry", ["int"], "void")
    .func("set_timeout", ["float"], "void")
    .func("set_general_prompt", ["str"], "void")
    .func("set_branch_prompt", ["str"], "void")
    .func("set_loop_prompt", ["str"], "void")
    .func("set_return_type_prompt", ["str", "str"], "void")
    .func("get_return_type_prompt", ["str"], "str")
    .func("set_decision_map", ["dict"], "void")
    .func("get_decision_map", [], "dict")
    .func("get_last_call_info", [], "dict")
    .func("get_scene_prompt", ["str"], "str")
    .func("set_scene_config", ["str", "dict"], "void")
    .func("set_global_intent", ["str"], "void")
    .func("clear_global_intents", [], "void")
    .func("remove_global_intent", ["str"], "void")
    .func("get_global_intents", [], "list")
    .func("get_current_intent_stack", [], "list")
    .func("mask", ["str"], "void")
)